baseurl = "https://cryos.net/"
languageCode = "en-us"
title = "Marcus D. Hanwell's Blog"
# Enable comments by entering your Disqus shortname
disqusShortname = "mhanwell"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-19476290-1"
# Define the number of posts per page
paginate = 10
footnotereturnlinkcontents = "↩"
theme = "hugo-icarus"
#theme = "blowfish"

[permalinks]
    post = "/:year/:month/:slug"
    archive = "/:slug/"

[params]
    # Tell me who you are
    author = "Marcus D. Hanwell"
    bio = "Programmer - Scientist - Open Source"
    location = "Wading River, NY, USA"
    site_description = "Views my own."
    copyright  = " Marcus D. Hanwell. Powered by [Hugo](//gohugo.io)."
    avatar = "images/mhanwell-profile.jpg"
    logo = ""

    # define which types of pages should be shown. By default the type with the most regular pages
    mainSections = ["post"]

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

    # Add custom assets with their paths relative to the static folder
	custom_css = []
	custom_js  = []

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "Home"
    link   = "/"

#[[params.menu]]
#    before = false
#    label  = "Tags"
#    link   = "tags/"

[[params.menu]]
    before = false
    label  = "Archive"
    link   = "archive/"

[[params.menu]]
    before = false
    label  = "Categories"
    link   = "categories/"

# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://github.com/cryos"


[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# created automatically.
    github          = "cryos"
#    gitlab          = "cryos"
#    bitbucket       = "cryos"
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = "mhanwell"
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
#    googleplus      = "MarcusHanwell"
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = ""
    googlescholar   = "r65_q0oAAAAJ"
    orcid           = "0000-0002-5851-5272"
#    twitter         = "mhanwell"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = true
    tags = true
    tag_cloud = true
