name: Build and deploy hugo blog
run-name: ${{ github.actor }} is testing out deployment
on:
  push:
    branches: [ $default-branch ]
  workflow_dispatch:

jobs:
  Build:
    name: Build hugo blog
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting up the steps to build and deploy the blog."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Install hugo
        run: |
          mkdir bin
          cd bin
          wget https://github.com/gohugoio/hugo/releases/download/v0.111.3/hugo_0.111.3_Linux-64bit.tar.gz -O hugo.tgz
          tar -zxvf hugo.tgz
          cd ..
      - name: Build blog
        run: ./bin/hugo
      - name: Install firebase tools
        run: curl -sL https://firebase.tools | bash
      - name: Deploy to firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only hosting --token ${FIREBASE_TOKEN}
      - run: echo "This job's status is ${{ job.status }}."

